package com.saltycodes.overgearedepicknights.items;

import com.saltycodes.overgearedepicknights.Mappings;
import com.saltycodes.overgearedepicknights.OvergearedEpicKnights;
//? if forge {
import net.minecraftforge.fml.ModList;
//?} else {
/*import net.neoforged.fml.ModList;
*///?}

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Every intermediate forging item (blade, head, prodd) this mod adds, together with all the data
 * the generators need: item ids, knapping/casting/forging/assembly recipes, tool types, blueprints,
 * models and language entries. Add an entry here and everything else follows.
 *
 * <p>Forging key specs:
 * <ul>
 *   <li>{@code ingot} – the material's forging ingredient (heated ingot item for iron/copper/steel,
 *       common ingot tag for the rest)</li>
 *   <li>{@code ingot_tag} – the material's common ingot tag, never the heated item</li>
 *   <li>{@code blade:<type>} – this mod's blade of {@code <type>} in the same material</li>
 *   <li>{@code item:<id>} / {@code tag:<id>} – a fixed item or tag</li>
 * </ul>
 * Assembly ingredients use {@code item:<id>} / {@code tag:<id>}.
 *
 * <p>Entries marked {@link Spec#addon()} belong to <em>Epic Knights: Addon</em>. Their items are only
 * registered when that mod is loaded and their data lands in the built-in {@code addon} datapack
 * (see {@code AddonDatapack}). The addon section is generated by {@code tools/derive_addon.py}.
 */
public enum BladeType {

    // ── Simple blades: '#' = material ingot, knappable from cobblestone ────────

    STYLET(spec("stylet", "Stiletto").cast(9).castableType()
            .knap("  x", "   ", "   ")
            .forge(3, "  #", "   ", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt")),

    SHORTSWORD(spec("shortsword", "Short Sword").cast(18).castableType()
            .knap("  x", " X ", "   ")
            .forge(4, "  #", " # ", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt")),

    KATZBALGER(spec("katzbalger", "Katzbalger").cast(18).castableType()
            .knap(" x ", " x ", "   ")
            .forge(4, " # ", " # ", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt")),

    PIKE(spec("pike", "Pike").part("Head").cast(9).castableType()
            .knap("   ", " x ", "   ")
            .forge(3, "   ", " # ", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:pole")),

    AHLSPIESS(spec("ahlspiess", "Ahlspiess").part("Head").cast(36)
            .knap("  x", "xx ", " x ")
            .forge(5, "  #", "## ", " # ").key('#', "ingot")
            .assemble("item:magistuarmory:pole")),

    LOCHABERAXE(spec("lochaberaxe", "Lochaber Axe").part("Head").cast(27)
            .knap("xx ", "x  ", "   ")
            .forge(5, "## ", "#  ", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:pole")),

    CONCAVEHALBERD(spec("concavehalberd", "Concave Halberd").part("Head").cast(36)
            .knap("xx ", "x x", "   ")
            .forge(6, "## ", "# #", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:pole", "tag:" + Mappings.COMMON + ":rods/wooden")),

    HEAVYMACE(spec("heavymace", "Heavy Mace").part("Head").cast(27)
            .knap(" xx", "  x", "   ")
            .forge(5, " ##", "  #", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt", "tag:" + Mappings.COMMON + ":rods/wooden")),

    HEAVYWARHAMMER(spec("heavywarhammer", "Heavy War Hammer").part("Head").cast(45)
            .knap("xx ", "x x", "x  ")
            .forge(7, "## ", "# #", "#  ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt", "tag:" + Mappings.COMMON + ":rods/wooden")),

    LUCERNHAMMER(spec("lucernhammer", "Lucerne Hammer").part("Head").cast(27)
            .knap("xx ", "  x", "   ")
            .forge(5, "## ", "  #", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt", "tag:" + Mappings.COMMON + ":rods/wooden")),

    MORGENSTERN(spec("morgenstern", "Morningstar").part("Head").cast(27)
            .knap(" x ", "x x", "   ")
            .forge(5, " # ", "# #", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt", "tag:" + Mappings.COMMON + ":rods/wooden")),

    // ── Compound blades: 'I' = ingot tag, '#' = shortsword blade of the same material ──
    //    (stone variants are crafted from cobblestone + stone shortsword blade instead)

    BASTARDSWORD(spec("bastardsword", "Bastard Sword").cast(18)
            .forge(5, "I  ", "#  ", "   ").key('I', "ingot_tag").key('#', "blade:shortsword")
            .stoneBlade("I", "#")
            .assemble("item:magistuarmory:hilt")),

    ESTOC(spec("estoc", "Estoc").cast(18)
            .forge(5, " I ", "#  ", "   ").key('I', "ingot_tag").key('#', "blade:shortsword")
            .stoneBlade(" I ", "#  ")
            .assemble("item:magistuarmory:hilt")),

    CLAYMORE(spec("claymore", "Claymore").cast(18)
            .forge(5, "I# ", "   ", "   ").key('I', "ingot_tag").key('#', "blade:shortsword")
            .stoneBlade("I#")
            .assemble("item:magistuarmory:hilt")),

    ZWEIHANDER(spec("zweihander", "Zweihander").cast(36)
            .forge(6, "  I", "I# ", " I ").key('I', "ingot_tag").key('#', "blade:shortsword")
            .stoneBlade("  I", "I# ", " I ")
            .assemble("item:magistuarmory:hilt")),

    GUISARME(spec("guisarme", "Guisarme").part("Head").cast(27)
            .forge(5, "#I ", "   ", "   ").key('I', "ingot_tag").key('#', "blade:shortsword")
            .stoneBlade("#I")
            .assemble("item:magistuarmory:pole")),

    // ── Single-material items with fixed ingredients ──────────────────────────

    BLACKSMITH_HAMMER(spec("blacksmith_hammer", "Blacksmith Hammer").part("Head").materials(BladeMaterial.STEEL)
            .result("magistuarmory:blacksmith_hammer").cast(45)
            .forge(7, "###", "# #", "   ").key('#', "ingot")
            .assemble("item:magistuarmory:hilt", "tag:" + Mappings.COMMON + ":rods/wooden")),

    BARBED_CLUB(spec("barbed_club", "Barbed Club").part("Head").materials(BladeMaterial.STEEL)
            .result("magistuarmory:barbedclub")   // no casting
            .forge(5, " ac", "aca", " a ").key('a', "item:overgeared:steel_nugget").key('c', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden")),

    PITCHFORK(spec("pitchfork", "Pitchfork").part("Tines").materials(BladeMaterial.STEEL)
            .result("magistuarmory:pitchfork").cast(7)
            .forge(3, "###", "###", " # ").key('#', "item:overgeared:steel_nugget")
            .assemble("item:magistuarmory:pole")),

    HEAVY_CROSSBOW(spec("heavy_crossbow", "Heavy Crossbow").suffix("_prodd").part("Prodd").materials(BladeMaterial.STEEL)
            .result("magistuarmory:heavy_crossbow").cast(27)
            .forge(5, "###", "   ", "   ").key('#', "ingot")
            .customAssembly()),   // shaped: prodd + string + tripwire hooks + pole

    MESSER_SWORD(spec("messer_sword", "Messer Sword").materials(BladeMaterial.IRON)
            .result("magistuarmory:messer_sword").cast(28)
            .forge(6, "IN ", "B  ", "   ")
            .key('I', "ingot").key('N', "tag:" + Mappings.COMMON + ":nuggets/iron").key('B', "blade:shortsword")
            .assemble("item:magistuarmory:hilt")),

    // ── Epic Knights: Addon (steel only; generated by tools/derive_addon.py) ──

    ARMING_SWORD_TYPE_XIII(spec("arming_sword_type_xiii", "Arming Sword Type XIII").addon()
            .cast(24)
            .forge(5, " N ", "N#N", "NNN")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    ARMING_SWORD_TYPE_XIV(spec("arming_sword_type_xiv", "Arming Sword Type XIV").addon()
            .cast(24)
            .forge(5, "NNN", "N#N", " N ")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    ARMING_SWORD_TYPE_XV(spec("arming_sword_type_xv", "Arming Sword Type XV").addon()
            .cast(24)
            .forge(5, " NN", "N#N", "NN ")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    BAR_MACE(spec("bar_mace", "Bar Mace").addon()
            .part("Head")
            .cast(36)
            .forge(6, " SS", "SSS", " S ")
            .key('S', "item:magistuarmory:small_steel_plate")
            .assemble("tag:magistuarmory:hilts")),
    BATTLEAXE(spec("battleaxe", "Battleaxe").addon()
            .part("Head")
            .cast(27)
            .forge(5, "II ", "I  ", "   ")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    BILLHOOK(spec("billhook", "Billhook").addon()
            .part("Head")
            .cast(11)
            .forge(3, "NP ", "  N", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .key('P', "item:overgeared:steel_plate")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    BOAR_SPEAR(spec("boar_spear", "Boar Spear").addon()
            .part("Head")
            .cast(11)
            .forge(3, "NI ", " N ", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:poles")),
    BOLLOCK_DAGGER(spec("bollock_dagger", "Bollock Dagger").addon()
            .cast(9)
            .castableType()
            .forge(3, "   ", " I ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    BROADAXE(spec("broadaxe", "Broadaxe").addon()
            .part("Head")
            .cast(27)
            .forge(5, " I ", "II ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:poles")),
    CAVALRY_SABER(spec("cavalry_saber", "Cavalry Saber").addon()
            .cast(36)
            .forge(6, " II", "II ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    CROW_BEAK(spec("crow_beak", "Crow's Beak").addon()
            .part("Head")
            .cast(19)
            .forge(4, "II ", "  N", "   ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:hilts")),
    CUTLASS(spec("cutlass", "Cutlass").addon()
            .cast(27)
            .forge(5, " II", "I  ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    DAGGER(spec("dagger", "Dagger").addon()
            .tooltype("ek_dagger")
            .cast(9)
            .castableType()
            .forge(3, "I  ", "   ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    DANEAXE(spec("daneaxe", "Daneaxe").addon()
            .part("Head")
            .cast(27)
            .forge(5, " P ", "PI ", "   ")
            .key('P', "item:overgeared:steel_plate")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:poles")),
    ENGLISH_POLEAXE(spec("english_poleaxe", "English Poleaxe").addon()
            .part("Head")
            .cast(27)
            .forge(5, "PI ", "  I", "   ")
            .key('P', "item:overgeared:steel_plate")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    EXECUTIONERS_SWORD(spec("executioners_sword", "Executioners Sword").addon()
            .cast(38)
            .forge(6, "  I", "NI ", "#N ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    FALCHION(spec("falchion", "Falchion").addon()
            .cast(38)
            .forge(6, "  I", " I ", "N#N")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    FAUCHARD(spec("fauchard", "Fauchard").addon()
            .part("Head")
            .cast(19)
            .forge(4, " PN", "  I", "   ")
            .key('P', "item:overgeared:steel_plate")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    FEDER(spec("feder", "Feder").addon()
            .cast(29)
            .forge(5, "   ", "NI ", "#N ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    FRANCISCA_AXE(spec("francisca_axe", "Francisca Axe").addon()
            .part("Head")
            .cast(18)
            .castableType()
            .forge(4, "II ", "   ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts", "tag:" + Mappings.COMMON + ":rods/wooden")),
    FRENCH_HALBERD(spec("french_halberd", "French Halberd").addon()
            .part("Head")
            .cast(19)
            .forge(4, " N ", "P P", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .key('P', "item:overgeared:steel_plate")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    GALLOWGLASS_AXE(spec("gallowglass_axe", "Gallowglass Axe").addon()
            .part("Head")
            .cast(27)
            .forge(5, " P ", "PP ", "   ")
            .key('P', "item:overgeared:steel_plate")
            .assemble("tag:magistuarmory:poles")),
    GERMAN_GREATSWORD(spec("german_greatsword", "German Greatsword").addon()
            .cast(45)
            .forge(6, " I ", "I#I", "   ")
            .key('I', "ingot")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    GOEDENDAG(spec("goedendag", "Goedendag").addon()
            .part("Head")
            .cast(9)
            .castableType()
            .forge(3, "  I", "   ", "   ")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden")),
    GRAND_FALCHION(spec("grand_falchion", "Grand Falchion").addon()
            .part("Head")
            .cast(36)
            .forge(6, " II", "II ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:poles")),
    HAMMER_SPEAR(spec("hammer_spear", "Hammer Spear").addon()
            .part("Head")
            .cast(25)
            .forge(5, "SNS", "S S", "   ")
            .key('S', "item:magistuarmory:small_steel_plate")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:magistuarmory:poles", "tag:" + Mappings.COMMON + ":rods/wooden")),
    ITALIAN_POLEAXE(spec("italian_poleaxe", "Italian Poleaxe").addon()
            .part("Head")
            .cast(19)
            .forge(4, "PN ", "  I", "   ")
            .key('P', "item:overgeared:steel_plate")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    KING_SWORD(spec("king_sword", "King's Sword").addon()
            .forge(6, "  I", "GI ", "#G ")
            .key('I', "ingot")
            .key('G', "tag:" + Mappings.COMMON + ":nuggets/gold")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    LANCE(spec("lance", "Lance").addon()
            .part("Head")
            .forge(3, "  N", "   ", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    LONG_SEAX(spec("long_seax", "Long Seax").addon()
            .cast(27)
            .forge(5, "  I", " I ", "I  ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    LONGSWORD(spec("longsword", "Longsword").addon()
            .cast(28)
            .forge(5, "N  ", "I  ", "#  ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    MACIEJOWSKI_MESSER(spec("maciejowski_messer", "Maciejowski Messer").addon()
            .cast(14)
            .forge(4, " NN", "SS ", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .key('S', "item:magistuarmory:small_steel_plate")
            .assemble("tag:magistuarmory:hilts")),
    ADDON_MESSER_SWORD(spec("messer_sword", "Messer Sword").addon()
            .cast(28)
            .forge(5, "IN ", "#  ", "   ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    MILITARY_FORK(spec("military_fork", "Military Fork").addon()
            .part("Head")
            .cast(19)
            .forge(4, "INI", "   ", "   ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    PARRYING_DAGGER(spec("parrying_dagger", "Parrying Dagger").addon()
            .cast(11)
            .forge(3, "   ", "NI ", " N ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    PARTISAN(spec("partisan", "Partisan").addon()
            .part("Head")
            .cast(11)
            .forge(3, "NIN", "   ", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    RAPIER(spec("rapier", "Rapier").addon()
            .cast(21)
            .forge(4, "  N", "NI ", "*N ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .key('*', "blade:stylet")
            .assemble("tag:magistuarmory:hilts")),
    RONDEL_DAGGER(spec("rondel_dagger", "Rondel Dagger").addon()
            .cast(9)
            .castableType()
            .forge(3, " I ", "   ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    ROUND_MACE(spec("round_mace", "Round Mace").addon()
            .part("Head")
            .cast(28)
            .forge(5, " IN", "  I", "I  ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:magistuarmory:hilts")),
    SABRE(spec("sabre", "Sabre").addon()
            .cast(29)
            .forge(5, " N ", " I ", "N# ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    SAXON_SWORD(spec("saxon_sword", "Saxon Sword").addon()
            .cast(20)
            .forge(4, "  N", " # ", "N  ")
            .key('N', "item:overgeared:steel_nugget")
            .key('#', "blade:shortsword")
            .assemble("tag:magistuarmory:hilts")),
    SCIMITAR(spec("scimitar", "Scimitar").addon()
            .cast(19)
            .forge(4, "IN ", "I  ", "   ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:magistuarmory:hilts")),
    SCYTHE(spec("scythe", "Scythe").addon()
            .cast(27)
            .forge(5, "II ", "  I", "   ")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden")),
    SHORT_SEAX(spec("short_seax", "Short Seax").addon()
            .cast(18)
            .castableType()
            .forge(4, " I ", "I  ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    SHORT_SPEAR(spec("short_spear", "Short Spear").addon()
            .part("Head")
            .cast(9)
            .castableType()
            .forge(3, " I ", "   ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:poles")),
    SICKLE(spec("sickle", "Sickle").addon()
            .cast(12)
            .forge(3, "NN ", "NI ", "   ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts")),
    SIDESWORD(spec("sidesword", "Sidesword").addon()
            .cast(19)
            .forge(4, "  N", " I ", "*  ")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .key('*', "blade:stylet")
            .assemble("tag:magistuarmory:hilts")),
    SWISS_HALBERD(spec("swiss_halberd", "Swiss Halberd").addon()
            .part("Head")
            .cast(28)
            .forge(5, "PN ", "P I", "   ")
            .key('P', "item:overgeared:steel_plate")
            .key('N', "item:overgeared:steel_nugget")
            .key('I', "ingot")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    SWORDBREAKER(spec("swordbreaker", "Swordbreaker").addon()
            .cast(13)
            .forge(4, " N ", "*N ", "NN ")
            .key('N', "item:overgeared:steel_nugget")
            .key('*', "blade:stylet")
            .assemble("tag:magistuarmory:hilts")),
    TWO_HANDED_EVENING_STAR(spec("two_handed_evening_star", "Two Handed Evening Star").addon()
            .part("Head")
            .cast(33)
            .forge(5, "SIS", "S S", "   ")
            .key('S', "item:magistuarmory:small_steel_plate")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:poles", "tag:" + Mappings.COMMON + ":rods/wooden")),
    TWO_HANDED_MESSER(spec("two_handed_messer", "Two Handed Messer").addon()
            .cast(20)
            .forge(4, " SS", "NSN", "   ")
            .key('S', "item:magistuarmory:small_steel_plate")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:magistuarmory:hilts")),
    VOULGE(spec("voulge", "Voulge").addon()
            .part("Head")
            .cast(20)
            .forge(4, "PN ", "P N", "   ")
            .key('P', "item:overgeared:steel_plate")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),
    WAR_AXE(spec("war_axe", "War Axe").addon()
            .part("Head")
            .cast(27)
            .forge(5, "II ", "I  ", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts", "tag:" + Mappings.COMMON + ":rods/wooden")),
    WAR_HAMMER(spec("war_hammer", "War Hammer").addon()
            .part("Head")
            .cast(27)
            .forge(5, "II ", "  I", "   ")
            .key('I', "ingot")
            .assemble("tag:magistuarmory:hilts", "tag:" + Mappings.COMMON + ":rods/wooden")),
    WELSH_GUISARME(spec("welsh_guisarme", "Welsh Guisarme").addon()
            .part("Head")
            .cast(20)
            .forge(4, " IN", "I N", "   ")
            .key('I', "ingot")
            .key('N', "item:overgeared:steel_nugget")
            .assemble("tag:" + Mappings.COMMON + ":rods/wooden", "tag:magistuarmory:poles")),

    ;

    // ────────────────────────────────────────────────────────────────────────

    private final String name;
    private final String displayName;
    private final String suffix;
    private final String part;
    private final String tooltype;
    private final boolean addon;
    private final String resultTemplate;
    private final Set<BladeMaterial> materials;
    private final int castingAmount;
    private final boolean castableType;
    private final String[] knapPattern;
    private final int forgeHammering;
    private final String[] forgePattern;
    private final Map<Character, String> forgeKeys;
    private final String[] assemblyIngredients;
    private final String[] stoneBladePattern;

    BladeType(Spec s) {
        this.name = s.name;
        this.displayName = s.displayName;
        this.suffix = s.suffix;
        this.part = s.part;
        this.tooltype = s.tooltype != null ? s.tooltype : s.name;
        this.addon = s.addon;
        this.resultTemplate = s.resultTemplate != null ? s.resultTemplate
                : (s.addon ? "magistuarmoryaddon" : "magistuarmory") + ":{mat}_" + s.name;
        this.materials = s.materials == null
                ? Collections.unmodifiableSet(EnumSet.allOf(BladeMaterial.class))
                : Collections.unmodifiableSet(EnumSet.copyOf(Arrays.asList(s.materials)));
        this.castingAmount = s.castingAmount;
        this.castableType = s.castableType;
        this.knapPattern = s.knapPattern;
        this.forgeHammering = s.forgeHammering;
        this.forgePattern = s.forgePattern;
        this.forgeKeys = Collections.unmodifiableMap(s.forgeKeys);
        this.assemblyIngredients = s.assemblyIngredients;
        this.stoneBladePattern = s.stoneBladePattern;
        if (forgePattern == null) throw new IllegalStateException(name + ": forge pattern missing");
        for (String row : forgePattern) {
            for (char c : row.toCharArray()) {
                if (c != ' ' && !forgeKeys.containsKey(c)) {
                    throw new IllegalStateException(name + ": no key for '" + c + "'");
                }
            }
        }
    }

    // ── Accessors ────────────────────────────────────────────────────────────

    /** Registry-name stem, e.g. {@code shortsword}; also the default tool type and blueprint id. */
    public String getName() { return name; }
    /** English name of the weapon, e.g. {@code Short Sword}. */
    public String getDisplayName() { return displayName; }
    /** Item-id suffix, {@code _blade} unless overridden. */
    public String getSuffix() { return suffix; }
    /** English name of the forged part, e.g. {@code Blade} or {@code Head}. */
    public String getPart() { return part; }
    /** Overgeared tool type / blueprint id. */
    public String getTooltype() { return tooltype; }
    public boolean isAddon() { return addon; }
    public Set<BladeMaterial> getMaterials() { return materials; }
    /** Metal units needed for casting (0 = no casting). */
    public int getCastingAmount() { return castingAmount; }
    public boolean hasCasting() { return castingAmount > 0; }
    /** Whether a clay/nether tool cast exists for this tool type (listed in casting_tooltypes). */
    public boolean isCastableType() { return castableType; }
    public String[] getKnapPattern() { return knapPattern; }
    public boolean hasKnapping() { return knapPattern != null; }
    public int getForgeHammering() { return forgeHammering; }
    public String[] getForgePattern() { return forgePattern; }
    /** Forging grid keys, see the class comment for the spec syntax. */
    public Map<Character, String> getForgeKeys() { return forgeKeys; }
    /** Extra shapeless-assembly ingredients, or {@code null} when the assembly is a custom shaped recipe. */
    public String[] getAssemblyIngredients() { return assemblyIngredients; }
    public String[] getStoneBladePattern() { return stoneBladePattern; }
    public boolean hasStoneBlade() { return stoneBladePattern != null; }

    /** Item id path of the blade for a material, e.g. {@code steel_shortsword_blade}. */
    public String itemPath(BladeMaterial mat) { return mat.getName() + "_" + name + suffix; }
    /** Full blade item id. */
    public String itemId(BladeMaterial mat) { return OvergearedEpicKnights.MODID + ":" + itemPath(mat); }
    /** The Epic Knights item the blade assembles into. */
    public String resultId(BladeMaterial mat) { return resultTemplate.replace("{mat}", mat.getName()); }
    /** English item name, e.g. {@code Steel Short Sword Blade}; single-material items omit the material. */
    public String itemName(BladeMaterial mat) {
        String base = displayName + " " + part;
        return materials.size() == 1 ? base : mat.getDisplayName() + " " + base;
    }
    /** The material the blueprint-crafting recipe uses as representative (steel if available). */
    public BladeMaterial canonicalMaterial() {
        BladeMaterial first = null;
        for (BladeMaterial m : materials) {
            if (m == BladeMaterial.STONE) continue;
            if (m == BladeMaterial.STEEL) return m;
            if (first == null) first = m;
        }
        return first != null ? first : BladeMaterial.STEEL;
    }

    // ── Availability (addon entries need Epic Knights: Addon) ─────────────────

    private static Boolean addonLoaded;

    public static boolean isAddonLoaded() {
        if (addonLoaded == null) {
            ModList list = ModList.get();
            addonLoaded = list != null && list.isLoaded(OvergearedEpicKnights.ADDON_MODID);
        }
        return addonLoaded;
    }

    /** True when this entry's items are registered in the current game (base entries always are). */
    public boolean isAvailable() { return !addon || isAddonLoaded(); }

    /** All entries whose items exist in this game. Use instead of {@link #values()} at runtime. */
    public static List<BladeType> active() {
        List<BladeType> out = new ArrayList<>();
        for (BladeType t : values()) if (t.isAvailable()) out.add(t);
        return out;
    }

    /** Entries of one section, regardless of availability (DataGen iterates these). */
    public static List<BladeType> of(boolean addon) {
        List<BladeType> out = new ArrayList<>();
        for (BladeType t : values()) if (t.addon == addon) out.add(t);
        return out;
    }

    // ── Spec builder ─────────────────────────────────────────────────────────

    private static Spec spec(String name, String displayName) { return new Spec(name, displayName); }

    static final class Spec {
        final String name, displayName;
        String suffix = "_blade", part = "Blade", tooltype, resultTemplate;
        boolean addon, castableType;
        BladeMaterial[] materials;
        int castingAmount, forgeHammering;
        String[] knapPattern, forgePattern, stoneBladePattern;
        String[] assemblyIngredients = new String[0];
        final Map<Character, String> forgeKeys = new LinkedHashMap<>();

        Spec(String name, String displayName) { this.name = name; this.displayName = displayName; }

        /** Epic Knights: Addon entry — steel only, result in the addon namespace, data in the addon pack. */
        Spec addon() { addon = true; materials = new BladeMaterial[]{BladeMaterial.STEEL}; return this; }
        Spec suffix(String s) { suffix = s; return this; }
        Spec part(String p) { part = p; return this; }
        Spec tooltype(String t) { tooltype = t; return this; }
        /** Assembly result id; {@code {mat}} is replaced by the material name. */
        Spec result(String template) { resultTemplate = template; return this; }
        Spec materials(BladeMaterial... m) { materials = m; return this; }
        Spec cast(int units) { castingAmount = units; return this; }
        Spec castableType() { castableType = true; return this; }
        Spec knap(String... rows) { knapPattern = rows; return this; }
        Spec forge(int hammering, String... rows) { forgeHammering = hammering; forgePattern = rows; return this; }
        Spec key(char c, String spec) { forgeKeys.put(c, spec); return this; }
        Spec assemble(String... ingredients) { assemblyIngredients = ingredients; return this; }
        Spec customAssembly() { assemblyIngredients = null; return this; }
        Spec stoneBlade(String... rows) { stoneBladePattern = rows; return this; }
    }
}
