modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Salty-Codes/Overgeared-Epic-Knights/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="overgeared_epic_knights.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# Comment out for DataGen
[[dependencies.${mod_id}]]
    modId="magistuarmory"
    mandatory=true
    versionRange="[10.11,)"
    ordering="AFTER"
    side="BOTH"

# Comment out for DataGen
[[dependencies.${mod_id}]]
    modId="overgeared"
    mandatory=true
    versionRange="[1.6.29,)"
    ordering="AFTER"
    side="BOTH"
